apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - env
        envFrom:
        - configMapRef:
            name: busybox
            optional: false
      - image: busybox
        command:
        - sleep
        - "3602"
        name: busybox
        resources: {}
---
apiVersion: v1
data:
  LOG_LEVEL: debug
kind: ConfigMap
metadata:
  name: busybox
  namespace: applications
