apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mux
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mux
  template:
    metadata:
      labels:
        run: mux
    spec:
      containers:
      - image: 752320408524.dkr.ecr.us-east-1.amazonaws.com/tjrtest
        command:
        - sleep
        - "3602"
        name: mux
        resources: {}
        envFrom:
        - configMapRef:
            name: mux
            optional: false
---
apiVersion: v1
data:
  LOG_LEVEL: debug
  TOUCH: "2"
kind: ConfigMap
metadata:
  name: mux
  namespace: applications
